when:
  branch: main

matrix:
  RUST_VERSION:
    - stable
    - beta
    - nightly

steps:
  test:
    image: rust
    commands:
      - rustup default ${RUST_VERSION}
      - cargo build --all --all-features --all-targets
      - if [ ${RUST_VERSION} = "nightly" ]; then cargo check -Z features=dev_dep; fi
      - cargo test
      - cargo test --no-default-features --tests
