when:
  branch: main

environment:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10
  
steps:
  fmt:
    image: rust
    commands:
      - rustup default stable
      - rustup component add rustfmt
      - cargo fmt --all --check
  
  lint:
    image: rust
    commands:
      - rustup default stable
      - rustup component add clippy
      - cargo clippy --all-features --all-targets
